[colors.bright]
black = "#727480"
blue = "#6c90a8"
cyan = "#528a9b"
green = "#999f63"
magenta = "#776690"
red = "#cb5760"
white = "#eeffff"
yellow = "#d4a067"

[colors.normal]
black = "#15121c"
blue = "#6c90a8"
cyan = "#528a9b"
green = "#999f63"
magenta = "#776690"
red = "#cb5760"
white = "#eeffff"
yellow = "#d4a067"

[colors.primary]
background = "#1b1b25"
foreground = "#dedede"

[font]
size = 12

[font.normal]
family = "JetBrains Mono"

[window]
opacity = 0.8
padding.x = 10
padding.y = 10

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
	{ key = "+", mods = "Control", action = "IncreaseFontSize" },
	{ key = ")", mods = "Control", action = "DecreaseFontSize" },
	{ key = "à", mods = "Control", action = "ResetFontSize" },
	{ key = "F11", mods = "None", action = "ToggleFullscreen" }
]

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux"]
